spring:
  application:
    name: gateway
  security:
    user:
      name: admin
      password: pass
      roles: ACTUATOR

server:
  port: 8080


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000

ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

zuul:
  ignoredServices: 'grpc-service'
  routes:
    rest-service:
      path: /api/r/**
      stripPrefix: false
      serviceId: rest-service

management:
  endpoint:
    health:
      show-details: when_authorized