spring:
  application:
    name: gateway
  security:
    user:
      name: admin
      password: pass
      roles: ACTUATOR

server:
  port: 8080


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 35000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 30000


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

zuul:
  ignoredServices: 'grpc-service'
  routes:
    rest-service:
      path: /api/r/**
      stripPrefix: false
      serviceId: rest-service

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: ["info","health","metrics","prometheus"]
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      percentiles:
        http:
          server:
            requests: [0.1, 0.2, 0.3, 0.4, 0.5, 0.7, 0.9, 0.95, 0.99, 0.999]
      sla:
        http:
          server:
            requests: [100ms, 200ms, 400ms, 600ms, 800ms, 1s, 2s, 5s]