spring:
  application:
    name: gateway
  security:
    user:
      name: admin
      password: pass
      roles: ACTUATOR

server:
  port: 8080


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 15000


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

zuul:
  ignoredServices: 'grpc-service'
  routes:
    rest-service:
      path: /api/r/**
      stripPrefix: false
      serviceId: rest-service

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: ["info","health","metrics","prometheus"]